INSERT INTO USER (ID,USERNAME,PASSWORD) VALUES (1,'admin','admin');

INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, AVAILABLE_QTY, UNIT_PRICE) VALUES(1, 'Product 1', 100, 50.0);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, AVAILABLE_QTY, UNIT_PRICE) VALUES(2, 'Product 2', 70, 500.0);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, AVAILABLE_QTY, UNIT_PRICE) VALUES(3, 'Product 3', 120, 250.0);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, AVAILABLE_QTY, UNIT_PRICE) VALUES(4, 'Product 4', 200, 750.0);
INSERT INTO PRODUCT(PRODUCT_ID, PRODUCT_NAME, AVAILABLE_QTY, UNIT_PRICE) VALUES(5, 'Product 5', 50, 5000.0);